// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
  interface Env {
    ALCHEMY_API_KEY: string;
    CDP_CLIENT_API_KEY: string;
    DB: D1Database;
  }
}
interface Env extends Cloudflare.Env {}
